# Generated by Django 3.2.9 on 2021-12-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_starwars_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwars_people',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='starwars_people',
            name='homeworld',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='starwars_people',
            name='mass',
            field=models.FloatField(null=True),
        ),
    ]
