# Generated by Django 3.2.9 on 2021-12-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211205_2304'),
        ('game', '0002_alter_transaction_cards_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_details', to='accounts.starwars_people'),
        ),
    ]
