# Generated by Django 3.2.9 on 2021-12-07 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_alter_transaction_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cards_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cards_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
