# Generated by Django 4.0 on 2021-12-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRecords',
            fields=[
                ('uuid_field', models.CharField(db_column='uuid_', max_length=75, primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('busniess_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('employee_range', models.CharField(blank=True, max_length=100, null=True)),
                ('legal_status', models.CharField(blank=True, max_length=50, null=True)),
                ('turnover', models.IntegerField(blank=True, null=True)),
                ('turnover_range', models.CharField(blank=True, max_length=100, null=True)),
                ('emails', models.CharField(blank=True, max_length=200, null=True)),
                ('phones', models.CharField(blank=True, max_length=150, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_url', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('incorporation_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('gsts', models.CharField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('modifiedby', models.CharField(blank=True, max_length=75, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
                ('extra', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company_records',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LinkedinTextDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(blank=True, max_length=300, null=True)),
                ('liid', models.CharField(blank=True, max_length=150, null=True)),
                ('e', models.CharField(blank=True, max_length=400, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('t', models.CharField(blank=True, max_length=300, null=True)),
                ('n', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'linkedin_text_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_field', models.CharField(db_column='uuid_', max_length=75)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_numbers', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('company_website', models.CharField(blank=True, max_length=200, null=True)),
                ('company_revenue', models.IntegerField(blank=True, null=True)),
                ('company_revenue_range', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('employee_range', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_info', models.CharField(blank=True, max_length=100, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person_records',
                'managed': False,
            },
        ),
    ]
