# Generated by Django 4.0 on 2022-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('address1', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('place_type', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('social_links', models.TextField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=30, null=True)),
                ('timing', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('google_place_id', models.CharField(blank=True, max_length=30, null=True)),
                ('place_link', models.CharField(blank=True, max_length=30, null=True)),
                ('cid', models.CharField(blank=True, max_length=30, null=True)),
                ('reviews_link', models.TextField(blank=True, null=True)),
                ('booking_link', models.TextField(blank=True, null=True)),
                ('place_id', models.TextField(blank=True, null=True)),
                ('global_plus_code', models.CharField(blank=True, max_length=30, null=True)),
                ('compound_plus_code', models.CharField(blank=True, max_length=30, null=True)),
                ('review_count', models.CharField(blank=True, max_length=5, null=True)),
                ('rating', models.CharField(blank=True, max_length=5, null=True)),
                ('createdate', models.DateTimeField(blank=True, null=True)),
                ('modifieddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
